name: debian-builder

on:
  push:
    branches:
      - main
    paths:
      - "Cargo.toml"
      - "Cargo.lock"
      - "src/**"
      - "readme.md"
      - "builder.dockerfile"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
    steps:
      - uses: actions/checkout@v5
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - run: |
          docker build \
            --file ./builder.dockerfile \
            --output ./target/debian \
            --platform ${{ matrix.platform }} \
            .
